### ISSUE TITLE
favorite无法下载，会报错，请问如何解决

### ISSUE THREAD

**Issue by Galaxy888** [loadchange/amemv-crawler#134]
会报下列的错：
Traceback (most recent call last):
  File "amemv-video-ripper.py", line 526, in <module>
    CrawlerScheduler(content)
  File "amemv-video-ripper.py", line 145, in __init__
    self.scheduling()
  File "amemv-video-ripper.py", line 166, in scheduling
    self.download_user_videos(url)
  File "amemv-video-ripper.py", line 181, in download_user_videos
    video_count = self._download_user_media(user_id, dytk, url)
  File "amemv-video-ripper.py", line 350, in _download_user_media
    user_id, dytk, hostname, signature, favorite_folder, video_count)
  File "amemv-video-ripper.py", line 295, in __download_favorite_media
    contentJson = json.loads(res.content.decode('utf-8'))
  File "/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by zzpop** [comment]
同求解决，近几天都没法下了- -。前几天更新的版本也不行orz

**Comment by xingtaisui** [comment]
同求+1

**Comment by bugmakesprogress** [comment]
同样的错误,下不到喜欢的小姐姐,sad.

**Comment by bugmakesprogress** [comment]
临时解决方案就是直接用浏览器请求share-url.txt里的地址,然后f12打开控制台, 点击喜欢按钮,获取临时的_signature和dytk并替换__download_favorite_media方法里的这两个变量.这样就能下载了

**Comment by bugmakesprogress** [comment]
可以从第一个pull request里用我的更新代码. 貌似是签名有修改,全局替换成我的fuck-byted-acrawler.js就好了.就是下载速度挺慢的,全量下载建议用chrome headless拿到signature再请求

**Comment by Galaxy888** [comment]
> _signature和dytk

的确可以下载了，但就是下载下来的文件名不太对了。。。

**Comment by Galaxy888** [comment]
> 临时解决方案就是直接用浏览器请求share-url.txt里的地址,然后f12打开控制台, 点击喜欢按钮,获取临时的_signature和dytk并替换__download_favorite_media方法里的这两个变量.这样就能下载了

的确可以下载了，但就是下载下来的文件名不太对了。。。

**Comment by bugmakesprogress** [comment]
> > 临时解决方案就是直接用浏览器请求share-url.txt里的地址,然后f12打开控制台, 点击喜欢按钮,获取临时的_signature和dytk并替换__download_favorite_media方法里的这两个变量.这样就能下载了
> 
> 的确可以下载了，但就是下载下来的文件名不太对了。。。

用我新pull request的amemv-video-ripper.py替换原作者的同名文件
