### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by lao2017** [loadchange/amemv-crawler#136]
'node' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Traceback (most recent call last):
  File "D:/Yuanshiwork/xiaohongshu/amemv-crawler-master/amemv-video-ripper.py", line 527, in <module>
    CrawlerScheduler(content)
  File "D:/Yuanshiwork/xiaohongshu/amemv-crawler-master/amemv-video-ripper.py", line 149, in __init__
    self.scheduling()
  File "D:/Yuanshiwork/xiaohongshu/amemv-crawler-master/amemv-video-ripper.py", line 170, in scheduling
    self.download_user_videos(url)
  File "D:/Yuanshiwork/xiaohongshu/amemv-crawler-master/amemv-video-ripper.py", line 185, in download_user_videos
    video_count = self._download_user_media(user_id, dytk, url)
  File "D:/Yuanshiwork/xiaohongshu/amemv-crawler-master/amemv-video-ripper.py", line 319, in _download_user_media
    signature = self.generateSignature(str(user_id))
  File "D:/Yuanshiwork/xiaohongshu/amemv-crawler-master/amemv-video-ripper.py", line 154, in generateSignature
    return p.readlines()[0]
IndexError: list index out of range

**Comment by loadchange** [comment]
需要安装node

**Comment by lao2017** [comment]
谢谢




| |
应国庆
|
|
邮箱：gqv2009@163.com
|

签名由 网易邮箱大师 定制

On 06/01/2019 23:18, Asa wrote:

Closed #136.
