### ISSUE TITLE
centos 7 python3.6运行报错json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by reversefuture** [loadchange/amemv-crawler#146]
window.collectEvent('404_referral', {})

window.collectEvent('send');</script> 
Traceback (most recent call last):
  File "amemv-video-ripper.py", line 543, in <module>
    CrawlerScheduler(content)
  File "amemv-video-ripper.py", line 150, in __init__
    self.scheduling()
  File "amemv-video-ripper.py", line 164, in scheduling
    self.download_user_videos(url)
  File "amemv-video-ripper.py", line 179, in download_user_videos
    video_count = self._download_user_media(user_id, dytk, url)
  File "amemv-video-ripper.py", line 340, in _download_user_media
    res = self.requestWebApi(url, params)
  File "amemv-video-ripper.py", line 477, in requestWebApi
    return json.loads(content)
  File "/usr/local/python3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)

**Comment by CHEN-HONGLIN** [comment]
2019-06-25 我亲自解决了，可以批量下载收藏视频、不信 可以参见我的博客https://blog.csdn.net/chl191623691/article/details/90711539
