### ISSUE TITLE
tiktok现在不能下载了吗

### ISSUE THREAD

**Issue by duoduo0505** [loadchange/amemv-crawler#157]
tiktok现在不能下载了吗？下载了源码跑不起来。
报错：
window.collectEvent('404_referral', {})

window.collectEvent('send');</script>
Traceback (most recent call last):
  File "amemv-video-ripper.py", line 543, in <module>
    CrawlerScheduler(content)
  File "amemv-video-ripper.py", line 150, in __init__
    self.scheduling()
  File "amemv-video-ripper.py", line 164, in scheduling
    self.download_user_videos(url)
  File "amemv-video-ripper.py", line 179, in download_user_videos
    video_count = self._download_user_media(user_id, dytk, url)
  File "amemv-video-ripper.py", line 340, in _download_user_media
    res = self.requestWebApi(url, params)
  File "amemv-video-ripper.py", line 477, in requestWebApi
    return json.loads(content)
  File "C:\Program Files\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)

**Comment by cnscorpions** [comment]
可以的，作者在share-url.txt的地址都删除掉，换上自己的就行

**Comment by EnvoySir** [comment]
> 可以的，作者在share-url.txt的地址都删除掉，换上自己的就行

怎么获取url呀
