### ISSUE TITLE
抖音签名算法变了，我有，大家可以联系我，共同探讨

### ISSUE THREAD

**Issue by junges521** [loadchange/amemv-crawler#176]
抖音新版的xgorgon算法变了

**Comment by kakaka6c** [comment]
我无法运行此代码，结果只能得到：
{"Status Code": 0, "has_more": Yes, "aweme_list": []}
Download user media: 85860189461, results retry: 1.
{"Status Code": 0, "has_more": Yes, "aweme_list": []}
Download user media: 85860189461, results retry: 2.

**Comment by crazyfish1111** [comment]
是的 我今天也是
download user media: 58479215586, result retry: 196.
{"status_code": 0, "has_more": true, "aweme_list": []}
download user media: 58479215586, result retry: 197.
{"status_code": 0, "has_more": true, "aweme_list": []}
download user media: 58479215586, result retry: 198.
Traceback (most recent call last):
  File "amemv-video-ripper.py", line 529, in <module>
    CrawlerScheduler(content)
  File "amemv-video-ripper.py", line 151, in __init__
    self.scheduling()
  File "amemv-video-ripper.py", line 165, in scheduling
    self.download_user_videos(url)
  File "amemv-video-ripper.py", line 180, in download_user_videos
    video_count = self._download_user_media(user_id, dytk, url)
  File "amemv-video-ripper.py", line 322, in _download_user_media
    res = self.requestWebApi(url, params)
  File "amemv-video-ripper.py", line 455, in requestWebApi
    content = res.content.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 4: invalid continuation byte

**Comment by oldstorm** [comment]
请问下有解决办法吗 遇到同样的问题

**Comment by junges521** [comment]
qq联系， 1570207752
