### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 5: invalid start byte

### ISSUE THREAD

**Issue by cheuhyakuroku** [loadchange/amemv-crawler#187]
Traceback (most recent call last):
  File "amemv-video-ripper.py", line 529, in <module>
    CrawlerScheduler(content)
  File "amemv-video-ripper.py", line 151, in __init__
    self.scheduling()
  File "amemv-video-ripper.py", line 165, in scheduling
    self.download_user_videos(url)
  File "amemv-video-ripper.py", line 175, in download_user_videos
    dytk = get_dytk(url)
  File "amemv-video-ripper.py", line 115, in get_dytk
    dytk = re.findall("dytk: '(.*)'", res.content.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 5: invalid start byte

**Comment by majormulfunction018** [comment]
HI I have the same issue as you do.Did you find a solution?

**Comment by hpplayer** [comment]
```
https://stackoverflow.com/questions/49702214/python-requests-response-encoded-in-utf-8-but-cannot-be-decoded
```
This post will be helpful.
But the script will still fail when parsing the response.
