### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 1: invalid start byte请问要如何处理

### ISSUE THREAD

**Issue by LiuGuoJiang** [loadchange/amemv-crawler#189]
Traceback (most recent call last):
  File "amemv-video-ripper.py", line 529, in <module>
    CrawlerScheduler(content)
  File "amemv-video-ripper.py", line 151, in __init__
    self.scheduling()
  File "amemv-video-ripper.py", line 165, in scheduling
    self.download_user_videos(url)
  File "amemv-video-ripper.py", line 175, in download_user_videos
    dytk = get_dytk(url)
  File "amemv-video-ripper.py", line 115, in get_dytk
    dytk = re.findall("dytk: '(.*)'", res.content.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 1: invalid start byte

**Comment by LiuGuoJiang** [comment]
@loadchange

**Comment by shipsywor** [comment]
@LiuGuoJiang 

```
https://www.iesdouyin.com/share/music/6536362398318922509?app=aweme&iid=30337873848
```

Add above url in `share-url.txt`


In the repo make sure to replace:

```
"accept-encoding": "gzip, deflate, br",

```

with this:

```
"accept-encoding": "gzip, deflate",

```

Run it.
