### ISSUE TITLE
fuck byted-acrawler

### ISSUE THREAD

**Issue by CnKore-zzb** [LoadChange/amemv-crawler#19]
fuck byted-acrawler什么意思，node小白。。。。

**Comment by qicaiyun** [comment]
python3 amemv-video-ripper.py Kanhaoshu

很多id会有如下报错：

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "amemv-video-ripper.py", line 31, in run
    self.download(medium_type, uri, download_url, target_folder)
  File "amemv-video-ripper.py", line 49, in download
    self._download(uri, 'video', download_url, target_folder)
  File "amemv-video-ripper.py", line 84, in _download
    print("Failed to retrieve %s from %s.\n" % medium_url)
TypeError: not enough arguments for format string

**Comment by LoadChange** [comment]
我也是小白，我猜测signature呢是抖音的同学防止太简单的去抓取视频所增加的一个字段，前后台约定用某种策略来检查这个字段的有效性，所以我们为了生成一个合格的signature 就需要下载抖音生成signature的这个js，在我们本地运行一下就可以了。
qicaiyun 的问题跟这个issues貌似没什么关系哦，去拉新的代码，搜索接口开启了mas算法验证，现在需要使用分享链接下载，具体读一下readme
