### ISSUE TITLE
用pycharm运行出现这个错误

### ISSUE THREAD

**Issue by wsxxc007** [loadchange/amemv-crawler#43]
'node' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Traceback (most recent call last):
  File "C:/Users/500/Desktop/github/amemv-crawler-master/amemv-crawler-master/amemv-video-ripper.py", line 411, in <module>
    CrawlerScheduler(content)
  File "C:/Users/500/Desktop/github/amemv-crawler-master/amemv-crawler-master/amemv-video-ripper.py", line 128, in __init__
    self.scheduling()
  File "C:/Users/500/Desktop/github/amemv-crawler-master/amemv-crawler-master/amemv-video-ripper.py", line 150, in scheduling
    self.download_challenge_videos(challenge)
  File "C:/Users/500/Desktop/github/amemv-crawler-master/amemv-crawler-master/amemv-video-ripper.py", line 165, in download_challenge_videos
    video_count = self._download_challenge_media(challenge)
  File "C:/Users/500/Desktop/github/amemv-crawler-master/amemv-crawler-master/amemv-video-ripper.py", line 276, in _download_challenge_media
    signature = self.generateSignature(str(challenge_id))
  File "C:/Users/500/Desktop/github/amemv-crawler-master/amemv-crawler-master/amemv-video-ripper.py", line 138, in generateSignature
    return p.readlines()[0]
IndexError: list index out of range

**Comment by loadchange** [comment]
检查一下你的node环境？
