### ISSUE TITLE
下载challenge的分享链接出现问题

### ISSUE THREAD

**Issue by Jet-JI** [loadchange/amemv-crawler#45]
可以下载大概十几个视频，但接下来就会报错，查了一下好像是超过最大递归次数，但深层原因就不知道了
Traceback (most recent call last):
  File "amemv-video-ripper.py", line 412, in <module>
    CrawlerScheduler(content)
  File "amemv-video-ripper.py", line 128, in __init__
    self.scheduling()
  File "amemv-video-ripper.py", line 150, in scheduling
    self.download_challenge_videos(challenge)
  File "amemv-video-ripper.py", line 165, in download_challenge_videos
    video_count = self._download_challenge_media(challenge)
  File "amemv-video-ripper.py", line 309, in _download_challenge_media
    video_count = get_aweme_list()
  File "amemv-video-ripper.py", line 305, in get_aweme_list
    return get_aweme_list(contentJson.get('cursor'), video_count)
  File "amemv-video-ripper.py", line 305, in get_aweme_list
    return get_aweme_list(contentJson.get('cursor'), video_count)
  File "amemv-video-ripper.py", line 305, in get_aweme_list
    return get_aweme_list(contentJson.get('cursor'), video_count)
  [Previous line repeated 947 more times]
  File "amemv-video-ripper.py", line 298, in get_aweme_list
    res = requests.get(url, headers=self.headers)
  File "D:\Anaconda3\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "D:\Anaconda3\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda3\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "D:\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "D:\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "D:\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "D:\Anaconda3\lib\site-packages\urllib3\connection.py", line 337, in connect
    cert = self.sock.getpeercert()
  File "D:\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 348, in getpeercert
    'subjectAltName': get_subj_alt_name(x509)
  File "D:\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 196, in get_subj_alt_name
    ext = cert.extensions.get_extension_for_class(
  File "D:\Anaconda3\lib\site-packages\cryptography\utils.py", line 158, in inner
    result = func(instance)
  File "D:\Anaconda3\lib\site-packages\cryptography\hazmat\backends\openssl\x509.py", line 137, in extensions
    self._backend, self._x509
  File "D:\Anaconda3\lib\site-packages\cryptography\hazmat\backends\openssl\decode_asn1.py", line 249, in parse
    value = handler(backend, ext_data)
  File "D:\Anaconda3\lib\site-packages\cryptography\hazmat\backends\openssl\decode_asn1.py", line 428, in _decode_subject_alt_name
    _decode_general_names_extension(backend, ext)
  File "D:\Anaconda3\lib\site-packages\cryptography\x509\extensions.py", line 1008, in __init__
    self._general_names = GeneralNames(general_names)
  File "D:\Anaconda3\lib\site-packages\cryptography\x509\extensions.py", line 964, in __init__
    if not all(isinstance(x, GeneralName) for x in general_names):
  File "D:\Anaconda3\lib\site-packages\cryptography\x509\extensions.py", line 964, in <genexpr>
    if not all(isinstance(x, GeneralName) for x in general_names):
  File "D:\Anaconda3\lib\abc.py", line 182, in __instancecheck__
    if subclass in cls._abc_cache:
  File "D:\Anaconda3\lib\_weakrefset.py", line 75, in __contains__
    return wr in self.data
RecursionError: maximum recursion depth exceeded in comparison

**Comment by zhu-jz** [comment]
因为经常会得到`{'status_code': 0, 'has_more': True, 'aweme_list': []}`，就以为是下一页了，可以判断一下是否有max_cursor这个key

**Comment by Jet-JI** [comment]
@zhu-jz contentJson里貌似没有max_cursor这个key

**Comment by steven7851** [comment]
API 一段时间内有访问次数限制，`'count': '9',` 改成 `'count': '32767',`，可以减少访问次数
https://github.com/loadchange/amemv-crawler/blob/2f87a6c8c0ba041f082435f4b8d4f2fdb31ba042/amemv-video-ripper.py#L282

**Comment by NinjaMoon** [comment]
@steven7851 都修改了该是不行

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 56, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fcc384c1240>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.douyin.com', port=443): Max retries exceeded with url: /aweme/v1/aweme/favorite/?user_id=85176385417&count=32767&max_cursor=1531849044000&aid=1128&_signature=U6XiQgAACPSsWh29ZbTOIlOl4l%0A&dytk=6d26627a458fe3aebb342c015d397229 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcc384c1240>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "amemv-video-ripper.py", line 412, in <module>
    CrawlerScheduler(content)
  File "amemv-video-ripper.py", line 128, in __init__
    self.scheduling()
  File "amemv-video-ripper.py", line 147, in scheduling
    self.download_videos(params)
  File "amemv-video-ripper.py", line 159, in download_videos
    video_count = self._download_user_media(number, dytk)
  File "amemv-video-ripper.py", line 260, in _download_user_media
    video_count = get_favorite_list()
  File "amemv-video-ripper.py", line 256, in get_favorite_list
    return get_favorite_list(contentJson.get('max_cursor'), video_count)
  File "amemv-video-ripper.py", line 256, in get_favorite_list
    return get_favorite_list(contentJson.get('max_cursor'), video_count)
  File "amemv-video-ripper.py", line 256, in get_favorite_list
    return get_favorite_list(contentJson.get('max_cursor'), video_count)
  [Previous line repeated 122 more times]
  File "amemv-video-ripper.py", line 249, in get_favorite_list
    res = requests.get(url, headers=self.headers)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.douyin.com', port=443): Max retries exceeded with url: /aweme/v1/aweme/favorite/?user_id=85176356781&count=32767&max_cursor=1531849044000&aid=1128&_signature=U6XiQgAACPSsWh29ZbTOIlOl4l%0A&dytk=6d26627a458fe3aebb342c015d397229 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcc384c1240>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

**Comment by steven7851** [comment]
看起来像是域名问题 www.douyin.com、www.iesdouyin.com 都改成 www.amemv.com 应该可以
