### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by renever** [loadchange/amemv-crawler#48]
看不懂 js，请问该怎么修正？谢谢。
环境：windows 7， python 3.7

E:\Code\Python3\amemv-crawler-master\fuck-byted-acrawler.js:5
    let e = {}
        ^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
Traceback (most recent call last):
  File ".\amemv-video-ripper.py", line 412, in <module>
    CrawlerScheduler(content)
  File ".\amemv-video-ripper.py", line 128, in __init__
    self.scheduling()
  File ".\amemv-video-ripper.py", line 147, in scheduling
    self.download_videos(params)
  File ".\amemv-video-ripper.py", line 159, in download_videos
    video_count = self._download_user_media(number, dytk)
  File ".\amemv-video-ripper.py", line 201, in _download_user_media
    signature = self.generateSignature(str(user_id))
  File ".\amemv-video-ripper.py", line 138, in generateSignature
    return p.readlines()[0]
IndexError: list index out of range

**Comment by taojian1989** [comment]
我也是这个错~

**Comment by godsonhand** [comment]
升级node吧。

**Comment by Asurada2015** [comment]
现在我也报这个错误
