### ISSUE TITLE
按照提示，clone，安装requirements, 最终运行出错

### ISSUE THREAD

**Issue by toneytang** [loadchange/amemv-crawler#58]
麻烦看看是哪一步出了错呢？
按你的提示安装的。谢谢

 git clone https://github.com/loadchange/amemv-crawler.git
cd amemv-crawler
pip install -r requirements.txt

Requirement already satisfied: certifi>=2017.4.17 in c:\users\globalock1\appdata\local\programs\python\python37-32\lib\site-packages (from requests>=2.10.0->-r requirements.txt (line 1)) (2018.4.16)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\globalock1\appdata\local\programs\python\python37-32\lib\site-packages (from requests>=2.10.0->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in c:\users\globalock1\appdata\local\programs\python\python37-32\lib\site-packages (from requests>=2.10.0->-r requirements.txt (line 1)) (1.23)
Installing collected packages: PySocks
  Running setup.py install for PySocks: started
    Running setup.py install for PySocks: finished with status 'done'
Successfully installed PySocks-1.6.8

$ python amemv-video-ripper.py
'node' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "amemv-video-ripper.py", line 462, in <module>
    CrawlerScheduler(content)
  File "amemv-video-ripper.py", line 139, in __init__
    self.scheduling()
  File "amemv-video-ripper.py", line 183, in scheduling
    self.download_videos(params)
  File "amemv-video-ripper.py", line 195, in download_videos
    video_count = self._download_user_media(number, dytk)
  File "amemv-video-ripper.py", line 270, in _download_user_media
    signature = self.generateSignature(str(user_id))
  File "amemv-video-ripper.py", line 149, in generateSignature
    return p.readlines()[0]
IndexError: list index out of range

**Comment by toneytang** [comment]
my computer problem. sorry.
