### ISSUE TITLE
运行报错，请指教

### ISSUE THREAD

**Issue by Asurada2015** [loadchange/amemv-crawler#68]
Traceback (most recent call last):
  File "C:/Users/cloud/Desktop/information security/amemv-crawler-master/amemv-video-ripper.py", line 415, in <module>
    CrawlerScheduler(content)
  File "C:/Users/cloud/Desktop/information security/amemv-crawler-master/amemv-video-ripper.py", line 111, in __init__
    self.scheduling()
  File "C:/Users/cloud/Desktop/information security/amemv-crawler-master/amemv-video-ripper.py", line 138, in scheduling
    self.download_videos(params)
  File "C:/Users/cloud/Desktop/information security/amemv-crawler-master/amemv-video-ripper.py", line 150, in download_videos
    video_count = self._download_user_media(number, dytk)
  File "C:/Users/cloud/Desktop/information security/amemv-crawler-master/amemv-video-ripper.py", line 223, in _download_user_media
    signature = self.generateSignature(str(user_id))
  File "C:/Users/cloud/Desktop/information security/amemv-crawler-master/amemv-video-ripper.py", line 122, in generateSignature
    return p.readlines()[0]
IndexError: list index out of range

**Comment by Asurada2015** [comment]
使用的是python3.5.0,windows10操作系统
share_url.txt文件中按照您推荐的分享的不是单个文件，而是完整的用户名
nodejs安装的最新版本
http://v.douyin.com/dsaPn8/,
http://v.douyin.com/dsabCK/
求您指教

**Comment by loadchange** [comment]
p.readlines()[0]

现在在 `125` 行 😅,  代码没更新啊， 你的错误是因为没拿到node的结果呀，


检查一下你的终端可以正常使用 `node` 吗?

`node fuck-byted-acrawler.js xxx`

这样运行一下试试呢 有没正确返回

**Comment by Asurada2015** [comment]
运行了node以后是这个结果
![2018-10-02_194838](https://user-images.githubusercontent.com/14261323/46346994-93a35780-c67c-11e8-80aa-ddf68722663d.jpg)

**Comment by Asurada2015** [comment]
可以了，我这次先按照您的建议运行了node命令
现在再执行py文件，结果如下：
![2018-10-02_195314](https://user-images.githubusercontent.com/14261323/46347220-5db2a300-c67d-11e8-99ad-22e262cab9df.jpg)
![2018-10-02_195326](https://user-images.githubusercontent.com/14261323/46347225-61dec080-c67d-11e8-906f-a5a191527ce5.jpg)
问题解决了，谢谢~
