### ISSUE TITLE
求助小白mac下运行报错

### ISSUE THREAD

**Issue by zhaoruicong** [loadchange/amemv-crawler#89]
Traceback (most recent call last):
  File "/Users/ki/Downloads/amemv-crawler-master/amemv-video-ripper.py", line 461, in <module>
    CrawlerScheduler(content)
  File "/Users/ki/Downloads/amemv-crawler-master/amemv-video-ripper.py", line 113, in __init__
    self.scheduling()
  File "/Users/ki/Downloads/amemv-crawler-master/amemv-video-ripper.py", line 133, in scheduling
    for url in self.numbers: self.download_user_videos(url)
  File "/Users/ki/Downloads/amemv-crawler-master/amemv-video-ripper.py", line 143, in download_user_videos
    video_count = self._download_user_media(user_id, dytk, url)
  File "/Users/ki/Downloads/amemv-crawler-master/amemv-video-ripper.py", line 268, in _download_user_media
    signature = self.generateSignature(str(user_id))
  File "/Users/ki/Downloads/amemv-crawler-master/amemv-video-ripper.py", line 118, in generateSignature
    return p.readlines()[0]
IndexError: list index out of range

**Comment by loadchange** [comment]
安装一下 `node` 环境
